# Generated by Django 5.2.13 on 2026-04-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('b2c', 'B2C'), ('b2b', 'B2B'), ('balance', 'Balance')], max_length=16)),
                ('command_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='submitted', max_length=16)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('party_a', models.CharField(blank=True, max_length=64)),
                ('party_b', models.CharField(blank=True, max_length=64)),
                ('account_reference', models.CharField(blank=True, max_length=128)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('occasion', models.CharField(blank=True, max_length=255)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('originator_conversation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('callback_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DarajaRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='POST', max_length=16)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='daraja.darajatransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DarajaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_type', models.CharField(choices=[('b2c_result', 'B2C Result'), ('b2c_timeout', 'B2C Timeout'), ('b2b_result', 'B2B Result'), ('b2b_timeout', 'B2B Timeout'), ('balance_result', 'Balance Result'), ('balance_timeout', 'Balance Timeout')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('originator_conversation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='daraja.darajatransaction')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
