# Generated by Django 5.2.13 on 2026-04-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0002_darajauitestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='darajauitestrun',
            name='execution_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=16),
        ),
    ]
