# Generated by Django 5.2.13 on 2026-04-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0003_darajauitestrun_execution_environment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='darajatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('originator_conversation_id', ''), _negated=True), fields=('originator_conversation_id',), name='daraja_unique_nonempty_originator_conversation_id'),
        ),
    ]
