# Generated by Django 5.2.13 on 2026-05-18 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0004_darajatransaction_daraja_unique_nonempty_originator_conversation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaPaybillConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybill_number', models.CharField(max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=16)),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=20)),
                ('initiator_name', models.CharField(max_length=255)),
                ('initiator_password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_paybills_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_paybills_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paybill_number'],
                'constraints': [models.UniqueConstraint(fields=('paybill_number', 'environment'), name='daraja_unique_paybill_per_environment')],
            },
        ),
    ]
