"""
Django settings for settlement project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env", overwrite=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "DJANGO_SECRET_KEY",
    default="django-insecure-c-(356fmygufb-jk1$o8tdk9qm_=rqx7s!b_%w@c)&!nw))wg*",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=[
        "127.0.0.1",
        "localhost",
        "zetu.laivoo.com",
    ],
)

CSRF_TRUSTED_ORIGINS = [
    'https://zetu.laivoo.com',
    'https://*.laivoo.com',
    'http://localhost:81',
    'http://localhost',
    'http://127.0.0.1:81',
    'http://127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth_ui",
    "allauth",
    "allauth.account",
    "rest_framework",
    "daraja",
    "widget_tweaks",
    "slippers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "settlement.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "settlement.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = env.str("DB_ENGINE", default="django.db.backends.sqlite3")
DB_NAME = env.str("DB_NAME", default=str(BASE_DIR / "db.sqlite3"))

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": DB_NAME,
        "USER": env.str("DB_USER", default=""),
        "PASSWORD": env.str("DB_PASSWORD", default=""),
        "HOST": env.str("DB_HOST", default=""),
        "PORT": env.str("DB_PORT", default=""),
        "CONN_MAX_AGE": env.int("DB_CONN_MAX_AGE", default=60),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/staticfiles/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "landing"

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ALLAUTH_UI_THEME = "light"


# Django REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
}


# Daraja / M-Pesa settings
DARAJA_ENV = env.str("DARAJA_ENV", default="sandbox").strip().lower()
if DARAJA_ENV not in {"sandbox", "production"}:
    raise ValueError("DARAJA_ENV must be either 'sandbox' or 'production'.")

DARAJA_CALLBACK_BASE_URL = env.str("DARAJA_CALLBACK_BASE_URL", default="https://example.com").rstrip("/")
DARAJA_TIMEOUT_SECONDS = env.int("DARAJA_TIMEOUT_SECONDS", default=30)
DARAJA_TOKEN_REFRESH_BUFFER_SECONDS = env.int(
    "DARAJA_TOKEN_REFRESH_BUFFER_SECONDS", default=60
)

DARAJA_CALLBACK_PATHS = {
    "b2c_result": "api/daraja/b2c/callback/result/",
    "b2c_timeout": "api/daraja/b2c/callback/timeout/",
    "b2b_result": "api/daraja/b2b/callback/result/",
    "b2b_timeout": "api/daraja/b2b/callback/timeout/",
    "balance_result": "api/daraja/balance/callback/result/",
    "balance_timeout": "api/daraja/balance/callback/timeout/",
}
DARAJA_CALLBACK_URLS = {
    key: f"{DARAJA_CALLBACK_BASE_URL}/{path}"
    for key, path in DARAJA_CALLBACK_PATHS.items()
}

_DARAJA_PREFIX = f"DARAJA_{DARAJA_ENV.upper()}"
DARAJA_CONFIG = {
    "environment": DARAJA_ENV,
    "consumer_key": env.str(f"{_DARAJA_PREFIX}_CONSUMER_KEY", default=""),
    "consumer_secret": env.str(f"{_DARAJA_PREFIX}_CONSUMER_SECRET", default=""),
    "shortcode": env.str(f"{_DARAJA_PREFIX}_SHORTCODE", default=""),
    "initiator_name": env.str(f"{_DARAJA_PREFIX}_INITIATOR_NAME", default=""),
    "initiator_password": env.str(f"{_DARAJA_PREFIX}_INITIATOR_PASSWORD", default=""),
    "certificate_path": env.str(
        f"{_DARAJA_PREFIX}_CERTIFICATE_PATH",
        default=str(
            BASE_DIR
            / "security"
            / ("SandboxCertificate.cer" if DARAJA_ENV == "sandbox" else "ProductionCertificate.cer")
        ),
    ),
    "callback_urls": DARAJA_CALLBACK_URLS,
    "timeout_seconds": DARAJA_TIMEOUT_SECONDS,
    "token_refresh_buffer_seconds": DARAJA_TOKEN_REFRESH_BUFFER_SECONDS,
}
