"""
Django settings for settlement project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: list[str]) -> list[str]:
    raw = os.getenv(name)
    if not raw:
        return default
    return [item.strip() for item in raw.split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-c-(356fmygufb-jk1$o8tdk9qm_=rqx7s!b_%w@c)&!nw))wg*",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    [
        "127.0.0.1",
        "localhost",
        "zetu.laivoo.com",
    ],
)

CSRF_TRUSTED_ORIGINS = ['https://zetu.laivoo.com', 'https://*.laivoo.com']



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth_ui",
    "allauth",
    "allauth.account",
    "rest_framework",
    "daraja",
    "widget_tweaks",
    "slippers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "settlement.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "settlement.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "landing"

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ALLAUTH_UI_THEME = "light"


# Django REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
}


# Daraja / M-Pesa settings
DARAJA_ENV = os.getenv("DARAJA_ENV", "sandbox").strip().lower()
if DARAJA_ENV not in {"sandbox", "production"}:
    raise ValueError("DARAJA_ENV must be either 'sandbox' or 'production'.")

DARAJA_CALLBACK_BASE_URL = os.getenv("DARAJA_CALLBACK_BASE_URL", "https://example.com").rstrip("/")
DARAJA_TIMEOUT_SECONDS = int(os.getenv("DARAJA_TIMEOUT_SECONDS", "30"))
DARAJA_TOKEN_REFRESH_BUFFER_SECONDS = int(
    os.getenv("DARAJA_TOKEN_REFRESH_BUFFER_SECONDS", "60")
)

DARAJA_CALLBACK_PATHS = {
    "b2c_result": "api/daraja/b2c/callback/result/",
    "b2c_timeout": "api/daraja/b2c/callback/timeout/",
    "b2b_result": "api/daraja/b2b/callback/result/",
    "b2b_timeout": "api/daraja/b2b/callback/timeout/",
    "balance_result": "api/daraja/balance/callback/result/",
    "balance_timeout": "api/daraja/balance/callback/timeout/",
}
DARAJA_CALLBACK_URLS = {
    key: f"{DARAJA_CALLBACK_BASE_URL}/{path}"
    for key, path in DARAJA_CALLBACK_PATHS.items()
}

_DARAJA_PREFIX = f"DARAJA_{DARAJA_ENV.upper()}"
DARAJA_CONFIG = {
    "environment": DARAJA_ENV,
    "consumer_key": os.getenv(f"{_DARAJA_PREFIX}_CONSUMER_KEY", ""),
    "consumer_secret": os.getenv(f"{_DARAJA_PREFIX}_CONSUMER_SECRET", ""),
    "shortcode": os.getenv(f"{_DARAJA_PREFIX}_SHORTCODE", ""),
    "initiator_name": os.getenv(f"{_DARAJA_PREFIX}_INITIATOR_NAME", ""),
    "initiator_password": os.getenv(f"{_DARAJA_PREFIX}_INITIATOR_PASSWORD", ""),
    "certificate_path": os.getenv(
        f"{_DARAJA_PREFIX}_CERTIFICATE_PATH",
        str(
            BASE_DIR
            / "security"
            / ("SandboxCertificate.cer" if DARAJA_ENV == "sandbox" else "ProductionCertificate.cer")
        ),
    ),
    "callback_urls": DARAJA_CALLBACK_URLS,
    "timeout_seconds": DARAJA_TIMEOUT_SECONDS,
    "token_refresh_buffer_seconds": DARAJA_TOKEN_REFRESH_BUFFER_SECONDS,
}
